version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      #- /
      - /Installer # for Installer/Dependabot.csproj
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
