version: 1

device-type: keyboard
log-level: debug

monitors:
  - description: Dell S2722QC(HDMI1)
    serial-number: 9XTRLD3
    attach:
      code: 0x60
      value: 0x11
    detach:
      code: 0x60
      value: 0x12

  - description: Dell S2722QC(HDMI1)
    serial-number: 51TRLD3
    attach:
      code: 0x60
      value: 0x11
    detach:
      code: 0x60
      value: 0x12
