name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: windows-2022

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: 6.0.x

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3

      - name: Build sources
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory coverage

      - name: Upload unit test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/**/coverage.cobertura.xml
          if-no-files-found: error

      - name: Prepare installer
        working-directory: bin/Release
        run: Rename-Item -Path ShadowKVM.msi -NewName ShadowKVM-${{ steps.version_step.outputs.fullSemVer }}.msi

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: bin/Release/ShadowKVM-*.msi
          if-no-files-found: error

  coverage-report:
    name: Create Coverage Report
    runs-on: ubuntu-24.04 # these steps do not support Windows
    needs: build

    permissions:
      pull-requests: write

    steps:
      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          # TODO fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

  release:
    name: Release
    runs-on: windows-2022
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $version = "${{ github.ref_name }}" -Replace "^v", ""
          gh release create "${{ github.ref_name }}" `
            --title "Shadow KVM ${version}" `
            --draft `
            --generate-notes `
            --verify-tag

      - name: Download installer
        uses: actions/download-artifact@v4
        with:
          name: installer
          path: installer

      - name: Upload installer to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $msi = Get-ChildItem -Path installer -Filter "ShadowKVM-*.msi" `
            | Select-Object -ExpandProperty FullName
          gh release upload "${{ github.ref_name }}" "$msi"
