name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: windows-2022

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: 6.0.x

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3

      - name: Build sources
        run: dotnet build --configuration Release

      - name: Prepare installer
        working-directory: bin/Release
        run: Rename-Item -Path ShadowKVM.msi -NewName ShadowKVM-${{ steps.version_step.outputs.fullSemVer }}.msi

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: bin/Release/ShadowKVM-*.msi
          if-no-files-found: error

  release:
    name: Release
    runs-on: windows-2022
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $version = $GITHUB_REF_NAME -Replace "^v", ""
          gh release create "$GITHUB_REF_NAME" `
            --title "Shadow KVM ${version}" `
            --draft `
            --fail-on-no-commits `
            --generate-notes `
            --verify-tag

      - name: Download installer
        uses: actions/download-artifact@v4
        with:
          name: installer
          path: installer

      - name: Upload installer to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $msi = Get-ChildItem -Path installer -Filter "ShadowKVM-*.msi" `
            | Select-Object -ExpandProperty FullName
          gh release upload "$GITHUB_REF_NAME" "$msi"
