name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: windows-2022

    permissions:
      pull-requests: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: 6.3.x

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v4

      - name: Lint sources
        run: dotnet format --verify-no-changes

      - name: Build sources
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test --configuration Release --no-build

      - name: Generate Coverage Report
        uses: clearlyip/code-coverage-report-action@v6
        id: code_coverage_report_action
        if: ${{ github.actor != 'dependabot[bot]'}}
        with:
          filename: bin/Release/coverage.cobertura.xml
          badge: true

      - name: Add Coverage Comment to PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.code_coverage_report_action.outputs.file != '' && github.event_name == 'pull_request' && (success() || failure())
        with:
          path: code-coverage-results.md

      - name: Prepare installer
        run: |
          Remove-Item -Path bin, obj -Recurse -Force
          dotnet build Installer/Installer.wixproj --configuration Release
          Rename-Item -Path bin/Release/ShadowKVM.msi -NewName ShadowKVM-${{ steps.version_step.outputs.fullSemVer }}.msi

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: bin/Release/ShadowKVM-*.msi
          if-no-files-found: error

  release:
    name: Release
    runs-on: windows-2022
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $version = "${{ github.ref_name }}" -Replace "^v", ""
          gh release create "${{ github.ref_name }}" `
            --title "Shadow KVM ${version}" `
            --draft `
            --generate-notes `
            --verify-tag

      - name: Download installer
        uses: actions/download-artifact@v5
        with:
          name: installer
          path: installer

      - name: Upload installer to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $msi = Get-ChildItem -Path installer -Filter "ShadowKVM-*.msi" `
            | Select-Object -ExpandProperty FullName
          gh release upload "${{ github.ref_name }}" "$msi"
